### ISSUE TITLE
ActionClient states

### ISSUE THREAD

**Issue by AmandineMa** [SpyrosKou/rosjava_actionlib#2]
Hello,

First of all, thank you for all the work you've done on this package. I had given up to use it because I had found bugs in the other forks. Now, I'm trying to see if I can use yours :)

Since you've made a lot of improvements, I suggest one more : wouldn't it be more coherent with the state machine described in [here](http://wiki.ros.org/actionlib/DetailedDescription#Client_Description) and the python version of the package, to instantiate a client state machine only when a new goal is sent (line code in python [here](https://github.com/ros/actionlib/blob/c3b2bd84f07ff54c36033c92861d3b63b7420590/actionlib/src/actionlib/action_client.py#L460)) ? I have not studied the code enough to know if it's possible. But at least, it would be more telling to have a state "NO_GOAL" instead of having the state "ERROR" when starting the client.

Best,
amdia

**Comment by AmandineMa** [comment]
And I just tried, when a goal is preempted by a new one, it then remains to ERROR. The states it goes through are:
start action client : ERROR
send first goal : ACTIVE
send second goal: ERROR
receive result for second goal : remains at ERROR

**Comment by SpyrosKou** [comment]
Hello,

Thank you very much for your feedback. I hope you find this work useful.
Indeed currently the code goes through exactly the state changes that you describe. 
However instead of the 8 states described in [here](http://wiki.ros.org/actionlib/DetailedDescription#Client_Description) the ClientState enum includes 13 states. One of them is the [ERROR](https://github.com/SpyrosKou/rosjava_actionlib/blob/3a9a2d20a80e496ae707ecf5510a2fd135061d97/src/main/java/com/github/rosjava_actionlib/ClientState.java#L28) state.
An quick observation is that some of the additional states map to transitions. 

The transitions you describe seem correct.
There are also some additional steps which I list below.
The ActionClient starts in the Error state. 
However at this point the client object has been constructed, but is not connected to the ActionLib server.
At this point it is not yet an active client but once it connects to a server, and it is OK to send a goal, the client should go to a "WAITING_FOR_GOAL" state.
Currently when the client connects to the server, the status listener can update the status. See [here](https://github.com/SpyrosKou/rosjava_actionlib/blob/3a9a2d20a80e496ae707ecf5510a2fd135061d97/src/main/java/com/github/rosjava_actionlib/ActionClient.java#L288)
This server initiated transition needs to be checked, I am not sure that it actually  changes the state (seems not to)

Also indeed the client will first set the client state to ERROR when a second goal is sent, but then the status will be updated by the server. This leads to the previous situation, where server seems not to change the client status.

What is the behavior of the client you are trying to achieve? Could you provide a simple use case?
If you also have JUNIT tests for what you describe, feel free to upload them. I will try to look into the issue.

**Comment by AmandineMa** [comment]
Thank you for your answer :)
> At this point it is not yet an active client but once it connects to a server, and it is OK to send a goal, the client should go to a "WAITING_FOR_GOAL" state.

This is not what happens, the client remains at ERROR until it sends a goal. But it is OK that it does not not go in the state WAITING_FOR_GOAL_ACK since it should be in after sending a goal and not before. It is just that it is confusing that it starts with ERROR whereas there is no ERROR. The first time I saw that I was wondering what was going wrong. I would expect it to start with UNKNOWN_STATE or another (new) state called NO_GOAL or as the python/c++ APIs specify "getState() Returns LOST if this SimpleActionClient isn't tracking a goal."

> This server initiated transition needs to be checked, I am not sure that it actually changes the state (seems not to)

Indeed it does not change the state but I'm not sure it should (ref to the previous paragraph)

> Also indeed the client will first set the client state to ERROR when a second goal is sent, but then the status will be updated by the server. This leads to the previous situation, where server seems not to change the client status.

Yes, that's what I was trying to say, the client state remains to ERROR even though the status of the goal sent by the server progresses (active then succeeded)

> What is the behavior of the client you are trying to achieve? Could you provide a simple use case?

What I expect is a behavior similar to the one of python/c++ actionlib, that the client state evolves as it should:
construction of client -> LOST (or NO_GOAL or UNKNOWN_STATE) and not ERROR
connection to server -> LOST (or NO_GOAL or UNKNOWN_STATE) and not ERROR
new goal -> WAITING_FOR_GOAL_ACK
then all the transitions described on the ROS wiki, depending on what is received from the server
new goal whereas there is still an active goal -> PREEMPTED and then WAITING_FOR_GOAL_ACK and then all the "normal" transitions (as the active goal is preempted and then the new goal is accepted. right now the client state remains to ERROR)

> If you also have JUNIT tests for what you describe, feel free to upload them. I will try to look into the issue.

I don't have, and I'm not sure I'll have time to write some.

Thank you for your time !

**Comment by SpyrosKou** [comment]
> > At this point it is not yet an active client but once it connects to a server, and it is OK to send a goal, the client should go to a "WAITING_FOR_GOAL" state.
> 
> This is not what happens, the client remains at ERROR until it sends a goal. But it is OK that it does not not go in the state WAITING_FOR_GOAL_ACK since it should be in after sending a goal and not before. It is just that it is confusing that it starts with ERROR whereas there is no ERROR. The first time I saw that I was wondering what was going wrong. I would expect it to start with UNKNOWN_STATE or another (new) state called NO_GOAL or as the python/c++ APIs specify "getState() Returns LOST if this SimpleActionClient isn't tracking a goal."

Indeed this is what I meant, a state name, that describes the prior to "WAITING_FOR_GOAL_ACK " state. That could be a NO_GOAL as you mention used in other versions.


> > Also indeed the client will first set the client state to ERROR when a second goal is sent, but then the status will be updated by the server. This leads to the previous situation, where server seems not to change the client status.
> 
> Yes, that's what I was trying to say, the client state remains to ERROR even though the status of the goal sent by the server progresses (active then succeeded)

Thank you for checking that. It has been a while since I last checked this behavior but I can now say the following:
1. Whenever you set a new goal, the ClientGoalManager it always go to "WAITING_FOR_GOAL_ACK". It only passes from the ERROR internal State. See [here](https://github.com/SpyrosKou/rosjava_actionlib/blob/3a9a2d20a80e496ae707ecf5510a2fd135061d97/src/main/java/com/github/rosjava_actionlib/ClientGoalManager.java#L68).
2. The ClientStateMachine initial state is started in UNKNOWN_STATE. See [here](https://github.com/SpyrosKou/rosjava_actionlib/blob/3a9a2d20a80e496ae707ecf5510a2fd135061d97/src/main/java/com/github/rosjava_actionlib/ClientStateMachine.java#L38).
This is what it is going to be returned if the user tries to get the ClientState from the future. See [here](https://github.com/SpyrosKou/rosjava_actionlib/blob/3a9a2d20a80e496ae707ecf5510a2fd135061d97/src/main/java/com/github/rosjava_actionlib/ActionClientFuture.java#L95). 

In general the client has a goal status and a client status which are different. 

> > If you also have JUNIT tests for what you describe, feel free to upload them. I will try to look into the issue.
> 
> I don't have, and I'm not sure I'll have time to write some.

How did you test that the current behavior is not what was expected? Some coded tests will be helpful to know so I can try to understand how you use this library. If I find the time , I might add some but if you ever do have these tests, feel free to provide them. 

In any case I think that what you propose is correct and the major discrepancy is the actual naming of the ClientState.ERROR status. Inside this project it is always used as a NO_GOAL state. For this reason, I am going to verify this and then to rename the ERROR to NO_GOAL state.

**Comment by amdia** [comment]
To do test the behavior, I made a small change in your class SimpleClient.java and I ran it with RosRun, adding the startTasks method in the onStart method.

The output is

**Comment by AmandineMa** [comment]
To do test the behavior, I made a small change in your class SimpleClient.java and I ran it with RosRun, adding the startTasks method in the onStart method.

The code to send the first goal and then a new goal :
```
        final FibonacciActionGoal goalMessage = (FibonacciActionGoal) actionClient.newGoalMessage();
        final FibonacciGoal fibonacciGoal = goalMessage.getGoal();
        // set Fibonacci parameter
        fibonacciGoal.setOrder(6);
        System.out.println("Sending goal...");
        actionClient.sendGoal(goalMessage);
        final GoalID gid1 = goalMessage.getGoalId();
        System.out.println("Sent goal with ID: " + gid1.getId());
        System.out.println("Waiting for goal to complete...");
        int c = 0;
        
        while (actionClient.getGoalState() != ClientState.DONE && c<1000) {
            sleep(1);
            c++;
        }
        System.out.println("Sending a new goal...");
        actionClient.sendGoal(goalMessage);
        final GoalID gid2 = goalMessage.getGoalId();
        System.out.println("Sent goal with ID: " + gid2.getId());
        while (actionClient.getGoalState() != ClientState.DONE) {
        	sleep(1);
    	}
        System.out.println("Goal completed!\n");
```
The callback for the status :
```
    public void statusReceived(final GoalStatusArray status) {
            List<GoalStatus> statusList = status.getStatusList();
            for (GoalStatus gs : statusList) {
            	System.out.println("GoalID: " + gs.getGoalId().getId() + " -- GoalStatus: " + gs.getStatus() + " -- " + gs.getText());
            }
            System.out.println("Current state of our goal: " + actionClient.getGoalState());
    }
```
The output is below. 

> **Sending goal...**
> Sent goal with ID: /fibonacci_test_client-2
> Waiting for goal to complete...
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> Feedback from Fibonacci server: 0 1 1 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> Feedback from Fibonacci server: 0 1 1 2 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> **Sending a new goal...**
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 0 -- 
> Current state of our goal: PENDING
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 0 -- 
> Current state of our goal: PENDING
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 0 -- 
> Current state of our goal: PENDING
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 0 -- 
> Current state of our goal: PENDING
> Feedback from Fibonacci server: 0 1 1 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ACTIVE
> Got Fibonacci result sequence: 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Feedback from Fibonacci server: 0 1 1 2 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Feedback from Fibonacci server: 0 1 1 2 3 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Feedback from Fibonacci server: 0 1 1 2 3 5 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Feedback from Fibonacci server: 0 1 1 2 3 5 8 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Feedback from Fibonacci server: 0 1 1 2 3 5 8 13 
> GoalID: /fibonacci_test_client-2 -- GoalStatus: 2 -- 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 1 -- This goal has been accepted by the simple action server
> Current state of our goal: ERROR
> Got Fibonacci result sequence: 0 1 1 2 3 5 8 13 
> GoalID: /fibonacci_test_client-3 -- GoalStatus: 3 -- 
> Current state of our goal: ERROR

**Comment by SpyrosKou** [comment]
Thank you for providing this feedback.

I created a better example, more suitable to what you are looking for.
The client state that you are looking for should be the one you get from the [ActionFuture](https://github.com/SpyrosKou/rosjava_actionlib/blob/kinetic/src/main/java/com/github/rosjava_actionlib/ActionFuture.java) : [see line 91 of ClientServerStatusTest](https://github.com/SpyrosKou/rosjava_actionlib/blob/1bfdc40f44bb81770d1ca1bf8fe8ad1fb54afeb2/src/test/java/com/github/rosjava_actionlib/ClientServerStatusTest.java#L91) 

The state printed there is a "goal state". This implementation uses internally a goal state that is different than client state. 

I also added an example of using the client through an [ActionFuture](https://github.com/SpyrosKou/rosjava_actionlib/blob/kinetic/src/main/java/com/github/rosjava_actionlib/ActionFuture.java) as shown [in FutureBasedClient line 84](https://github.com/SpyrosKou/rosjava_actionlib/blob/1bfdc40f44bb81770d1ca1bf8fe8ad1fb54afeb2/src/test/java/com/github/rosjava_actionlib/FutureBasedClient.java#L84)
It is preferable to use an [ActionClient](https://github.com/SpyrosKou/rosjava_actionlib/blob/kinetic/src/main/java/com/github/rosjava_actionlib/ActionClient.java) like that rather than in the way the [SimpleClient](https://github.com/SpyrosKou/rosjava_actionlib/blob/kinetic/src/test/java/com/github/rosjava_actionlib/SimpleClient.java) is implemented.

**Comment by AmandineMa** [comment]
Perfect thank you ! :)

If I don't use the client state, what is the difference between using the result callback and ActionFuture if my class sending the goal instantiates the ActionClientListener?

**Comment by SpyrosKou** [comment]
You are welcome! I hope it is useful. 
They are slightly different.
- The ActionClientListener will be invoked every time the client receives a result (if you re-use the client)
- Every time you send a new goal with a client it returns an ActionFuture that tracks the particular goal.
